<a href="https://colab.research.google.com/github/KaterinaFox/PytonHomeworks/blob/main/Homework10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Задача.
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [1]:
import random
import pandas as pd
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  human
2  robot
3  robot
4  human

Перевод в one hot вид с помощью get_dummies

In [2]:
pd.get_dummies(data, drop_first=True)

    whoAmI_robot
0              1
1              0
2              1
3              1
4              0
5              0
6              0
7              1
8              1
9              0
10             1
11             1
12             0
13             1
14             1
15             0
16             0
17             1
18             0
19             0

Решение без использования get_dummies, с помощью функции.

In [3]:
def convert(row):
  if row == 'robot':
    return 1
  else:
    return 0

data['whoAmI_one_hot'] = data['whoAmI'].apply(convert)
data = data.drop(columns=['whoAmI'])
data.head(20)

    whoAmI_one_hot
0                1
1                0
2                1
3                1
4                0
5                0
6                0
7                1
8                1
9                0
10               1
11               1
12               0
13               1
14               1
15               0
16               0
17               1
18               0
19               0